/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ServiceType = IDL.Variant({
  'lawnMowing' : IDL.Null,
  'carWash' : IDL.Null,
});
export const Time = IDL.Int;
export const BookingInput = IDL.Record({
  'serviceType' : ServiceType,
  'date' : Time,
  'address' : IDL.Text,
});
export const BookingStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'serviceType' : ServiceType,
  'date' : Time,
  'address' : IDL.Text,
  'customerId' : IDL.Principal,
});

export const idlService = IDL.Service({
  'createBooking' : IDL.Func([BookingInput], [IDL.Nat], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getBooking' : IDL.Func([IDL.Nat], [Booking], ['query']),
  'getBookingsByServiceType' : IDL.Func(
      [ServiceType],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getBookingsByStatus' : IDL.Func(
      [BookingStatus],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ServiceType = IDL.Variant({
    'lawnMowing' : IDL.Null,
    'carWash' : IDL.Null,
  });
  const Time = IDL.Int;
  const BookingInput = IDL.Record({
    'serviceType' : ServiceType,
    'date' : Time,
    'address' : IDL.Text,
  });
  const BookingStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'serviceType' : ServiceType,
    'date' : Time,
    'address' : IDL.Text,
    'customerId' : IDL.Principal,
  });
  
  return IDL.Service({
    'createBooking' : IDL.Func([BookingInput], [IDL.Nat], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getBooking' : IDL.Func([IDL.Nat], [Booking], ['query']),
    'getBookingsByServiceType' : IDL.Func(
        [ServiceType],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getBookingsByStatus' : IDL.Func(
        [BookingStatus],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };