/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'status' : BookingStatus,
  'serviceType' : ServiceType,
  'date' : Time,
  'address' : string,
  'customerId' : Principal,
}
export interface BookingInput {
  'serviceType' : ServiceType,
  'date' : Time,
  'address' : string,
}
export type BookingStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export type ServiceType = { 'lawnMowing' : null } |
  { 'carWash' : null };
export type Time = bigint;
export interface _SERVICE {
  'createBooking' : ActorMethod<[BookingInput], bigint>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getBooking' : ActorMethod<[bigint], Booking>,
  'getBookingsByServiceType' : ActorMethod<[ServiceType], Array<Booking>>,
  'getBookingsByStatus' : ActorMethod<[BookingStatus], Array<Booking>>,
  'updateBookingStatus' : ActorMethod<[bigint, BookingStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];